CREATE TABLE IF NOT EXISTS farms_t (
	farmID INT AUTO_INCREMENT PRIMARY KEY,
	farmerID INT,
	CONSTRAINT farmsFK FOREIGN KEY (farmerID) 
		REFERENCES farmer_t(farmerID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
