INSERT IGNORE INTO Sensor (location, type)
VALUES
	('Dhaka', 'Temperature Sensor'),
	('Chittagong', 'Humidity Sensor'),
	('Khulna', 'GPS Sensor'),
	('Rajshahi', 'Shock Sensor'),
	('Rangpur', 'Temperature Sensor'),
	('Barishal', 'Humidity Sensor'),
	('Sylhet', 'GPS Sensor'),
	('Mymensingh', 'Shock Sensor'),
	('Dhaka', 'Temperature Sensor'),
	('Chittagong', 'Humidity Sensor'),
	('Khulna', 'GPS Sensor'),
	('Rajshahi', 'Shock Sensor'),
	('Rangpur', 'Temperature Sensor'),
	('Barishal', 'Humidity Sensor'),
	('Sylhet', 'GPS Sensor'),
	('Mymensingh', 'Shock Sensor'),
	('Dhaka', 'Temperature Sensor'),
	('Chittagong', 'Humidity Sensor'),
	('Khulna', 'GPS Sensor'),
	('Rajshahi', 'Shock Sensor'),
	('Rangpur', 'Temperature Sensor'),
	('Barishal', 'Humidity Sensor'),
	('Sylhet', 'GPS Sensor'),
	('Mymensingh', 'Shock Sensor');
